### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by x3evolutionx** [ark-mod/ArkBot#165]
2021-05-31 06:24:10,579 [27] WARN  ArkSavegameToolkitNet.Data.ExtraDataCharacterHandler - Expected int after properties to be 1 but found 0 at 231581893
2021-05-31 06:24:10,672 [8] WARN  ArkSavegameToolkitNet.Data.ExtraDataCharacterHandler - Expected int after properties to be 1 but found 0 at 233861212
2021-05-31 06:24:10,701 [8] WARN  ArkSavegameToolkitNet.Data.ExtraDataCharacterHandler - Expected int after properties to be 1 but found 0 at 233892837
2021-05-31 06:24:44,753 [7] ERROR ArkBot.Ark.ArkServerContext - Failed to update server (pve-rag)
System.ApplicationException: No tribe id
   at ArkSavegameToolkitNet.Domain.ArkTribe..ctor(IGameObject tribe, DateTime tribeSaveTime) in C:\Tobias\Repos\Own\ARK\ArkSavegameToolkitNet\ArkSavegameToolkitNet.Domain\ArkTribe.cs:line 77
   at ArkSavegameToolkitNet.Domain.ArkGameData.<>c.<Update>b__13_23(ArkTribe x) in C:\Tobias\Repos\Own\ARK\ArkSavegameToolkitNet\ArkSavegameToolkitNet.Domain\ArkGameData.cs:line 160
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ArkSavegameToolkitNet.Domain.ArkGameData.Update(CancellationToken ct, ArkPlayerExternal[] externalPlayerData, Boolean deferApplyNewData, ArkAnonymizeData anonymize) in C:\Tobias\Repos\Own\ARK\ArkSavegameToolkitNet\ArkSavegameToolkitNet.Domain\ArkGameData.cs:line 160
   at ArkBot.Ark.ArkServerContext.Update(Boolean manualUpdate, IConfig fullconfig, ISavegameBackupService savegameBackupService, IProgress`1 progress, CancellationToken ct)
2021-05-31 06:24:52,323 [7] ERROR ArkBot.Ark.ArkServerContext - Failed to update server (pve-isl)
System.ApplicationException: No tribe id
   at ArkSavegameToolkitNet.Domain.ArkTribe..ctor(IGameObject tribe, DateTime tribeSaveTime) in C:\Tobias\Repos\Own\ARK\ArkSavegameToolkitNet\ArkSavegameToolkitNet.Domain\ArkTribe.cs:line 77
   at ArkSavegameToolkitNet.Domain.ArkGameData.<>c.<Update>b__13_23(ArkTribe x) in C:\Tobias\Repos\Own\ARK\ArkSavegameToolkitNet\ArkSavegameToolkitNet.Domain\ArkGameData.cs:line 160
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ArkSavegameToolkitNet.Domain.ArkGameData.Update(CancellationToken ct, ArkPlayerExternal[] externalPlayerData, Boolean deferApplyNewData, ArkAnonymizeData anonymize) in C:\Tobias\Repos\Own\ARK\ArkSavegameToolkitNet\ArkSavegameToolkitNet.Domain\ArkGameData.cs:line 160
   at ArkBot.Ark.ArkServerContext.Update(Boolean manualUpdate, IConfig fullconfig, ISavegameBackupService savegameBackupService, IProgress`1 progress, CancellationToken ct)

**Comment by SirShaw** [comment]
Your error is "System.ApplicationException: No tribe id at ArkSavegameToolkitNet.Domain.ArkTribe..ctor(IGameObject tribe, DateTime tribeSaveTime) in" meaning there is probably a 0.arktribe file in your save directory somewhere.  If you remove this, it should correct the error.  Since this isnt something new and is covered on our discord, I am closing this.
