### ISSUE TITLE
error wile using command !linksteam using the beta release

### ISSUE THREAD

**Issue by JamieKG** [ark-mod/ArkBot#59]
Getting a error in the logs wile trying to run the command !linksteam and no feedback in discord
ive looked at all my settiings  and cant seem to find what ive done wrong any help would be much appreciated

```
"!linksteam" command error...
[HandleCommandAsync(C:\Repos\ArkBot\ArkBot\Discord\ArkDiscordBot.cs:202)]

<Exception>
  <Google.GoogleApiException>
    <Current>
      <ServiceName>urlshortener</ServiceName>
      <Error>Google.Apis.Requests.RequestError
Forbidden [403]
Errors [
	Message[Forbidden] Location[ - ] Reason[forbidden] Domain[global]
]
</Error>
      <HttpStatusCode>Forbidden</HttpStatusCode>
    </Current>
    <Message>Google.Apis.Requests.RequestError
Forbidden [403]
Errors [
	Message[Forbidden] Location[ - ] Reason[forbidden] Domain[global]
]
</Message>
    <TargetSite>Void MoveNext()</TargetSite>
    <Source>Google.Apis</Source>
    <StackTrace><![CDATA[at Google.Apis.Requests.ClientServiceRequest`1.<ParseResponse>d__27.MoveNext() in C:\Apiary\v1.20\google-api-dotnet-client\Src\Support\GoogleApis\Apis\Requests\ClientServiceRequest.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__23.MoveNext() in C:\Apiary\v1.20\google-api-dotnet-client\Src\Support\GoogleApis\Apis\Requests\ClientServiceRequest.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__22.MoveNext() in C:\Apiary\v1.20\google-api-dotnet-client\Src\Support\GoogleApis\Apis\Requests\ClientServiceRequest.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at ArkBot.Services.UrlShortenerService.<ShortenUrl>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at ArkBot.Commands.LinkSteamCommand.<LinkSteam>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_1.<<BuildCommand>g__ExecuteCallback1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Discord.Commands.CommandInfo.<ExecuteAsync>d__40.MoveNext()]]></StackTrace>
  </Google.GoogleApiException>
</Exception>
```

**Comment by JamieKG** [comment]
Ive changed a few things to try to get this to work but it still throws same error I can see the errors in the google console site but not really a reason as to why

**Comment by tsebring** [comment]
Yes, it's possible. Or the URL Shortener API was not enabled on the project you set up in Google Console.

Either way, it looks like new users will not be able to register and use the Google URL Shortener API anymore so it would have to be replaced with an alternative to maintain functionality.

> Starting May 30, 2018, only projects that have accessed URL Shortener APIs before today can create short links.

**Comment by JamieKG** [comment]
ok thanks for the reply the URL Shortener API is enabled as I can see the failures on the console.developers.google.com so I think it is due to the post that ive linked

**Comment by SirShaw** [comment]
this has been tested and corrected in the latest build.
